
function help {
	echo "NAME"
	echo "  otp - an easy-to-use command to managing one-time passwords."
	echo ""
	echo "SYNOPSIS"
	echo "  otp [command] service... username..."
	echo ""
	echo "DESCRIPTION"
	echo "  Manages multiple secret-keys used by an account for second-factor authentication (2FA)."
	echo "  Each secret-key/seed is stored in its own account file and is encrypted with the user's"
	echo "  pgp key. Account files are temporarily decrypted on-the-fly to generate fresh OTPs for"
	echo "  logging-in/accessing a 2FA-protected resource."
	echo ""
	echo "SUBCOMMANDS"
	echo "  list, -l"
	echo "      List the details for all current accounts."
	echo ""
	echo "  create, -c"
	echo "      Create a new account file for managing OTPs."
	echo ""
	echo "  generate, -g"
	echo "      Generate a new OTP for the specified account."
	echo ""
	echo "  export, -e"
	echo "      Display the secret-key for an account to setup another device or to migrate."
	echo ""
	echo "SEE ALSO"
	echo "  oathtool(1), gpg(1), gpg-agent(1)"
	echo ""
	echo "HISTORY"
	echo "  2020 - Written by alice seaborn (seaborn@lavabit.com)"
	echo ""
	echo "0.0.1                                 2022-10-19                                 MAN(1)"
}

